[package]
name = "sftpx"
version = "0.1.0"
edition = "2024"

[dependencies]
blake3 = "1.8.2"
clap = { version = "4.5.51", features = ["derive"] }
lz4_flex = { version = "0.12.0", default-features = false }
zstd = "0.13.3"
